using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Ahorcado
{
    public class AhorcadoComponents
    {
        public List<string> SetWords()
        {
            List<string> Word = new List<string>();
            Word.Add("arbol");
            Word.Add("perro");
            Word.Add("computadora");
            Word.Add("lapiz");
            Word.Add("pastel");
            Word.Add("manzana");
            Word.Add("pizza");
            Word.Add("dato");
            Word.Add("cacahuate");
            Word.Add("motocicleta");
            Word.Add("automovil");
            Word.Add("estudiante");
            Word.Add("cucaracha");
            Word.Add("cuarentena");
            Word.Add("rosa");
            Word.Add("pajaro");
            Word.Add("banco");
            Word.Add("masa");
            Word.Add("edificio");
            Word.Add("mesa");
            Word.Add("piso");
            Word.Add("puerta");
            Word.Add("casa");
            Word.Add("castillo");
            Word.Add("sopa");
            Word.Add("catedral");
            Word.Add("iglesia");
            Word.Add("monumento");
            Word.Add("mercado");
            Word.Add("carcel");
            Word.Add("prisionero");
            Word.Add("calle");
            Word.Add("cerveza");
            Word.Add("tequila");
            Word.Add("ron");
            Word.Add("jirafa");
            Word.Add("elefante");
            Word.Add("galeria");
            Word.Add("cine");
            Word.Add("hotel");
            Word.Add("hospital");
            Word.Add("farmacia");
            Word.Add("teatro");
            Word.Add("universidad");
            Word.Add("aeropuerto");
            Word.Add("cocina");
            Word.Add("facebook");
            Word.Add("tiktok");
            Word.Add("turista");
            Word.Add("sol");
            Word.Add("tigre");
            Word.Add("leon");
            Word.Add("paris");
            Word.Add("madrid");
            Word.Add("barcelona");
            Word.Add("liverpool");
            Word.Add("china");
            Word.Add("cama");
            Word.Add("cepillo");
            Word.Add("cortina ");
            Word.Add("cuchara");
            Word.Add("zorro");
            Word.Add("melon");
            Word.Add("sandia");
            Word.Add("xilofono");
            Word.Add("naranja");
            Word.Add("numero");
            Word.Add("zombi");
            Word.Add("esqueleto");
            Word.Add("muerto");
            Word.Add("vida");
            Word.Add("cartas");
            Word.Add("verdura");
            Word.Add("uva");
            Word.Add("agua");
            Word.Add("rojo");
            Word.Add("verde");
            Word.Add("purpura");
            Word.Add("negro");
            Word.Add("blanco");
            Word.Add("pierna");
            Word.Add("brazo");
            Word.Add("cabeza");
            Word.Add("futbol");
            Word.Add("tenis");
            Word.Add("baloncesto");
            Word.Add("escuela");
            Word.Add("ganador");
            Word.Add("perdedor");
            Word.Add("camino");
            Word.Add("torre");
            Word.Add("logo");
            Word.Add("juego");
            Word.Add("guitarra");
            Word.Add("botella");
            Word.Add("taza");
            Word.Add("plato");
            Word.Add("escritorio");
            Word.Add("juan");
            Word.Add("orlando");
            return Word;
        }
    }
}